# Uncomment the following line to enable OLED Displays
# CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_STUDIO_LOCKING=n
CONFIG_ZMK_LOGGING_MINIMAL=y
CONFIG_ZMK_POINTING=n
CONFIG_ZMK_INPUT_PROCESSOR_REPORT_RATE_LIMIT=n
CONFIG_ZMK_BEHAVIOR_RATE_LIMIT=n
