# Uncomment the following line to enable OLED Displays
# CONFIG_ZMK_DISPLAY=y
# Required for crosses_right trackball
CONFIG_ZMK_POINTING=y
CONFIG_ZMK_INPUT_PROCESSOR_REPORT_RATE_LIMIT=y
CONFIG_ZMK_INPUT_PROCESSOR_REPORT_RATE_LIMIT_DEFAULT=2
